# -*- coding: utf-8 -*-
"""metroticketbooking.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZrA1W_VHTXU8Z8n3qQNDDLr-y2yU97MN
"""

!pip install qrcode pillow

import qrcode
from PIL import Image
import random
import string
from datetime import datetime
import time
name = input("Enter your name:")
print("Welcome", name)
while True:
  choice = int(input("Select your choice \n 1.Book tickets \n 2.Platform Information \n 3.Exit "))
  if (choice == 1):
    stations_blueLine = ["AIRPORT",'MEENAMBAKKAM','NANGANALLUR ROAD','ALANDUR','GUINDY','LITTLE MOUNT','SAIDAPET','NANDANAM','TEYNAMPET','AG-DMS','THOUSAND LIGHT','LIC','GOVERNMENT ESTATE','CENTRAL','HIGH COURT','MANADY','WASHERMENPET']
    stations_greenline = ['ST THOMAS MOUNT','EKKATHUTHANGAL','ASHOK NAGAR','VADAPALANI','ARUMBAKKAM','CMBT','KOYEMBEDU','TIRUMANGALAM','ANNA NAGAR TOWER','ANNA NAGAR EAST','SHENOY NAGAR','PACHAYYAPAS COLLEGE','KILPAK','NEHRU PARK','EGMORE','CENTRAL']
    print(stations_blueLine)
    print(stations_greenline)
    station_entry = input("Enter your entry station: ")
    station_entry = station_entry.upper()
    station_exit = input("Enter your exit station: ")
    station_exit = station_exit.upper()
    while (station_entry not in stations_blueLine and station_entry not in stations_greenline):
        print("Invalid station. Please try again.")
        station_entry = input("Enter your entry station: ")
    while (station_exit not in stations_blueLine and station_exit not in stations_greenline):
        print("Invalid station. Please try again.")
        station_exit = input("Enter your exit station: ".upper())
    entry_index = -1
    exit_index = -1
    if (station_entry in stations_blueLine or station_entry in stations_greenline):
      if (station_entry in stations_blueLine):
        entry_index = stations_blueLine.index(station_entry)
      else:
        entry_index = stations_greenline.index(station_entry)
    if (station_exit in stations_blueLine or station_exit in stations_greenline):
      if (station_exit in stations_blueLine):
        exit_index = stations_blueLine.index(station_exit)
      else:
        exit_index = stations_greenline.index(station_exit)
    if not (entry_index<0 and exit_index<0):
      diff = abs(exit_index-entry_index)
    if (diff == 1):
      fare = 10
    elif (diff <= 3 and diff >1 ):
      fare = 20
    elif (diff <= 8 and diff >3):
      fare = 30
    elif (diff <= 15 and diff>8):
      fare = 40
    else:
      fare = 50
    print("Fare for one person: ",fare)
    admits = int(input("Enter number of admits: "))
    ticket_cost = fare*admits
    print("your total ticket cost is: ",ticket_cost)
    # for payment it will opens into UPI app
    print("REDIRECTING TO UPI")
    time.sleep(5)
    print("Payment Successful \n Please collect your ticket")
    n= admits
    codes = []
    for i in range(n):
        data = str(random.randint(1000, 9999))
        qr = qrcode.QRCode(version=1, box_size=10, border=5)
        qr.add_data(data)
        qr.make(fit=True)
        img = qr.make_image(fill_color="black", back_color="white")
        codes.append(img)
    for code in codes:
        code.show()
    print("--------------------------------------------")
    print("From : ",station_entry)
    print("To   : ",station_exit)
    print("Price: ",ticket_cost)
    print("Admits: ",admits)
    today = datetime.today().date()
    print("Date :",today.strftime("%d-%m-%Y"))
    print("--------------------------------------------")
    print("Thank you. Please visit again")
    break
  elif choice == 2:
    enter_destination = input("Enter your destination: ")
    enter_destination = enter_destination.upper()
    while(enter_destination not in stations_blueLine and enter_destination not in stations_greenline):
      print("Invalid station. Please try again.")
      enter_destination = input("Enter your destination: ")
    if (enter_destination in stations_blueLine):
      for i in stations_blueLine:
        print(i)
      print("The metro train for ",enter_destination," comes in platform 1")
    else:
      for j in stations_greenline:
        print(j)
      print("The metro train for ",enter_destination," comes in platform 2")
    print("Thank you. Please visit again.!!")
    break
  elif choice == 3:
    while (choice ==3):
      print("Thank You. Please visit again! ")
      break
    break
  else:
    print("Invalid choice of selection")